services:
  app:
    build: .
    container_name: sps-app
    environment:
      - VITE_API_BACKEND_URL=https://sps-api.iot.npic.edu.kh
      - VITE_API_BASE_URL=https://sps-api.iot.npic.edu/api/v1 
    image: "sps-app"
    ports:
      - 3000:80
    restart: unless-stopped